# Generated by Django 2.0 on 2019-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('Reference', 'Reference'), ('Borrowable', 'Borrowable')], default='', max_length=20)),
                ('genre', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
