# Generated by Django 2.0 on 2019-03-23 18:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Number',
            fields=[
                ('b_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('book_name', models.CharField(default='', max_length=255)),
                ('ISBN', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='The ISBN number should be 10 or 13 digit in length.', regex='^[0-9]{10}|[0-9]{13}$')])),
                ('description', models.TextField(default='')),
                ('edition', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('Reference', 'Reference'), ('Borrowable', 'Borrowable')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.Authors')),
                ('book_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Admin.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('f_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publish_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('s_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('st_name', models.CharField(default='', max_length=100)),
                ('ph_num', models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Phone no.', regex='^(98[0-9]{8}|97[0-9]{8})')])),
                ('email', models.EmailField(default='', max_length=254, validators=[django.core.validators.RegexValidator(message='Invalid email address!', regex='^([\\w]*[\\w\\.]*(?!\\.)@islingtoncollege.edu.np)')])),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('b_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.Book_Number')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.Students')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.Genres'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.Publishers'),
        ),
        migrations.AddField(
            model_name='book_number',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Books'),
        ),
    ]
