# Generated by Django 2.0 on 2019-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='edition',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default='', max_length=255),
        ),
    ]
