# Generated by Django 2.0 on 2019-03-31 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 7, 5, 41, 296519)),
        ),
    ]
