# Generated by Django 2.0 on 2019-03-31 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20190331_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='return_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 7, 24, 37, 404263)),
        ),
    ]
