# Generated by Django 2.0 on 2019-04-05 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20190331_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=10, max_length=2)),
                ('fine', models.IntegerField(default=5, max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='transactions',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 5, 55, 34, 956118)),
        ),
    ]
