# Generated by Django 2.0 on 2019-04-14 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20190405_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_number',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Taken', 'Taken'), ('Borrowed', 'Borrowed')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 5, 37, 14, 869126)),
        ),
    ]
