# Generated by Django 2.0 on 2019-04-15 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20190415_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 5, 48, 2, 801489)),
        ),
    ]
