# Generated by Django 2.0 on 2019-04-20 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_books_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(default=datetime.date(2019, 4, 21))),
                ('valid_till', models.DateTimeField(default=datetime.date(2019, 4, 22))),
                ('validation_status', models.IntegerField(default=0, max_length=1)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Books')),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Students')),
            ],
        ),
    ]
